services:
  diakem:
    container_name: ${INSTANCE_NAME}-diakem-control-center
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3015
      API_KEY: ${API_KEY:?API_KEY is required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      JWT_EXPIRATION_IN_DAYS: ${JWT_EXPIRATION_IN_DAYS:-2}
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD:?MONGO_PASSWORD is required}@diakem-db:27017/${INSTANCE_NAME}?authSource=admin
      STATIC_FRONTEND_PATH: ../frontend/dist
    ports:
      - "${APP_PORT:-3015}:3015"
    networks:
      - diakem-network
      - nginx-proxy-network

networks:
  diakem-network:
    external: true
  nginx-proxy-network:
    external: true